# 기본 설정 (공통)
ktor:
    application:
        modules:
            - com.swen.ApplicationKt.module

    deployment:
        port: ${?PORT:8080}

# 현재 활성화된 프로필
app:
    profile: ${?APP_PROFILE:local}

# 기본 로깅 설정
logging:
    level:
        root: INFO
        com.swen: INFO
        org.jetbrains.exposed: INFO