# 로컬 개발 환경 설정
external-api:
  naver:
    news:
      client-id: ${NAVER_CLIENT_ID}
      client-secret: ${NAVER_CLIENT_SECRET}
      base-url: "https://openapi.naver.com"
    
    hyperclova:
      api-key: ${NAVER_HYPERCLOVA_API_KEY}
      api-key-primary: ${NAVER_HYPERCLOVA_API_KEY_PRIMARY}
      api-gateway-url: ${NAVER_HYPERCLOVA_API_GATEWAY_URL}
      request-id: ${NAVER_HYPERCLOVA_REQUEST_ID:X-NCP-CLOVASTUDIO-REQUEST-ID}

# 로컬 MySQL 설정
database:
  mysql:
    host: ${DB_HOST:localhost}
    port: ${DB_PORT:3306}
    name: ${DB_NAME:news_db}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD}
    
  hikari:
    maximum-pool-size: 5
    minimum-idle: 1
    connection-timeout: 30000
    idle-timeout: 300000
    max-lifetime: 900000

# 로컬 개발용 로깅 (더 상세하게)
logging:
  level:
    root: DEBUG
    com.swen: DEBUG
    org.jetbrains.exposed.sql: DEBUG
    io.ktor.client: INFO
